name: build

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  esp32:
    name: ESP-IDF build (esp32)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.3.6
          target: esp32
          path: '.'
